# TODO: Must be Ansible (terraform?) managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 2s
  scrape_timeout: 5s

  external_labels:
    environment: monitoring.neuroops.link

rule_files:
  - /etc/prometheus/rules/*.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'node'
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: 'node_exporters'
    file_sd_configs:
     - files:
        - /etc/prometheus/targets.d/*.yml
        - /etc/prometheus/targets.d/*.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__, exporter_port]
        regex: (.+);(\d+)
        replacement: $1:$2
        target_label: __address__
      - regex: 'exporter_port'
        action: labeldrop
