version: '2'

networks:
  public-tier: {}


services:
  traefik:
    security_opt:
      - label=type:container_runtime_t
    image: traefik:v2.5
    container_name: "traefik"
    command: # FIXME: api must be secure
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.email=kosyta.keeper+le@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--metrics.prometheus=true"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - ./traefik:/etc/traefik:Z
    networks:
      - public-tier


